/// Flutter icons TripOnFont
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TripOnIcons
///      fonts:
///       - asset: fonts/TripOnIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class TripOnIcons {
  TripOnIcons._();

  static const _kFontFam = 'TripOnIcons';
  static const _kFontPkg = null;

  static const IconData xingxing =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xingxing1 =
      const IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dingzhiyou =
      const IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jiesongji =
      const IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feiji =
      const IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car =
      const IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guize =
      const IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData position_copy =
      const IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chuzuche =
      const IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mudedi =
      const IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bad =
      const IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shijian =
      const IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brand =
      const IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData good_1 =
      const IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shezhi =
      const IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weixin_denglu =
      const IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData yixuan =
      const IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feiji1 =
      const IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xiaoxi1 =
      const IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pingjia =
      const IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zhongping =
      const IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData baoche =
      const IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shouye2 =
      const IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData juli =
      const IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ertongzuoyijiekoux =
      const IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wenti =
      const IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hangcheng =
      const IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shouye1 =
      const IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wode =
      const IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gerenzhongxinwoderenwubiaozhuntouxianxing =
      const IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jinru =
      const IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData guanjia =
      const IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zichan =
      const IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youhuiquan =
      const IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jinhangzhong =
      const IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wode1 =
      const IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_left =
      const IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fenxiang =
      const IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData che =
      const IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order_copy =
      const IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wode2 =
      const IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData haoping =
      const IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xiaoxi2 =
      const IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData daizhifu =
      const IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xiaoxi =
      const IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
